### ISSUE TITLE
请问网上有视频吗？

### ISSUE THREAD

**Issue by zhaoxin111** [twcmchang/DLCV2018SPRING#1]
看到slides了，没看到videos，感觉教程很nice！

**Comment by twcmchang** [comment]
@zhaoxin111 的確是很棒的課! 不過上課沒有錄影，應該也沒有 video 可以看。倒是另外一門課 (machine learning and having it deep and structured, MLDS) 的李宏毅教授有 video 放在 youtube: https://www.youtube.com/channel/UC2ggjtuuWvxrHHHiaDH1dlQ 提供參考。
